version: "3.8"

services:

  online_shop:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: online_shop
    ports:
      - "3000:5173"
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/"]
      interval: 60s
      timeout: 10s
      retries: 5
    networks:
      - online_shop

networks:
  online_shop:
    driver: bridge
